---
title: "LondonSalesTurnover"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(lubridate)
```

```{r}
get_creds <- function() {
  jstring <-
    system(
      "aws secretsmanager get-secret-value --secret-id prod/db1/app --region us-east-1 --output json",
      intern = T
    )
  res <-
    jsonlite::fromJSON(jsonlite::fromJSON(paste0(jstring, collapse = ""))$SecretString)
  return(res)
}
get_con <- function(res) {
  con <-
    RPostgres::dbConnect(
      RPostgres::Postgres(),
      user = res$username,
      password = res$password,
      host = res$host,
      dbname = "propertydata",
      bigint = "numeric"
    )
  return(con)
}

#con <- get_con(get_creds())
#all_lisings <- tbl(con,"proc_listings") %>% collect()
```

```{r}
#saveRDS(all_lisings, "allistings.rds")
```

```{r}
#system("aws s3 cp allistings.rds s3://ukpd/property-analysis/alllistings.rds")
```


```{r}
w <- is.na(all_lisings$saledate)
all_lisings$saledate2 <- all_lisings$saledate
all_lisings$saledate2[w] <- all_lisings$listing_date[w]
w <- is.na(all_lisings$saledate2) & all_lisings$listing_status!="Last sold"
w[is.na(w)] <- FALSE
all_lisings$saledate2[w] <- all_lisings$date_scraped[w]

w <- is.na(all_lisings$trans_date) & all_lisings$listing_status!="Last sold"
w[is.na(w)] <- FALSE
all_lisings$saledate2[w] <- all_lisings$date_scraped[w]


all_lisings$listing_status[!is.na(all_lisings$lang_reg_id)] <- "Sold (LR)"
```


```{r}
sales <- filter(all_lisings, str_detect(tolower(listing_status), "sold"))
```

```{r}
summary(sales[is.na(sales$saledate),c('date_scraped','listing_date','saledate','trans_date')])
```
```{r}
sales2 <- filter(arrange(sales, desc(trans_date)), 
                 !duplicated(listing_key) & !is.na(trans_date))
```


```{r}
sales2$sale_year <- sales2$trans_date %>% year %>% as.factor
summary(sales2$sale_year)
```
```{r}
savelist <- aws.s3::s3readRDS("preprocess/diff/EC.rds",bucket="ukpd")
```

```{r}
library(glue)
```


```{r}
ec1 <- filter(sales2, str_detect(tolower(postcode), "^ec") & sale_year == 2021 & beds==1)
ec1 %>% select(property_key, address, postcode, trans_date, price_num) %>% arrange(desc(trans_date)) %>% 
  arrange(price_num)
```

```{r}
filter(all_lisings, postcode=="EC1M 6ET" & 
         trans_date > '2020-01-01' & 
         (!str_detect(price, "pcm") | is.na(price)) &
         (price_num > 10e3 | is.na(price_num))
       ) %>% 
  arrange(desc(trans_date)) %>% 
  select(trans_date, property_key, listing_key, address, price, price_num, listing_status, area, beds) %>% distinct()
```


```{r}
sale_statuses <- c("Sold subject to contract","Sold STC","Last sold", "Sold (LR)")
```

```{r}
aa <- filter(all_lisings, property_key=="7956474" & (!str_detect(price,"pcm") | is.na(price)) & 
               (price_num > 10e3 | is.na(price_num))) %>% 
  distinct(trans_date, listing_status, price, price_num, area, beds) %>% 
  mutate(sale=listing_status %in% sale_statuses) %>% 
  arrange(desc(trans_date))
aa
```
```{r}
ab <- aa[aa$sale,]
ab
```


```{r}
if(nrow(ab) > 1) ac <- aa[between(aa$trans_date, ab$trans_date[2], ab$trans_date[1]) & !aa$sale,] else 
  ac <- aa[(aa$trans_date < ab$trans_date[1]) & !aa$sale,] 

min_price <- min(ac$price_num)
max_price <- max(ac$price_num)
time_to_sell <- difftime(ab$trans_date[1], min(ac$trans_date, na.rm=T), units = "days")
time_to_sell
```

